# Week 1 Deliverable

##### Read all the Listing files from 2024, 2025, and 2026. First, combined all the Listing files by year and then combined all of the list year files all into one large csv file for Listing data.

In [2]:
import pandas as pd

In [3]:
list1 = pd.read_csv("CRMLSListing202401.csv")
list2 = pd.read_csv("CRMLSListing202402.csv")
list3 = pd.read_csv("CRMLSListing202403.csv")
list4 = pd.read_csv("CRMLSListing202404.csv")
list5 = pd.read_csv("CRMLSListing202405.csv")
list6 = pd.read_csv("CRMLSListing202406.csv")
list7 = pd.read_csv("CRMLSListing202407.csv")
list8 = pd.read_csv("CRMLSListing202408.csv")
list9 = pd.read_csv("CRMLSListing202409.csv")
list10 = pd.read_csv("CRMLSListing202410.csv")
list11 = pd.read_csv("CRMLSListing202411.csv")
list12 = pd.read_csv("CRMLSListing202412.csv")

list2024 = pd.concat([list1,list2,list3,list4,list5,list6,list7,list8,list9,list10,list11,list12])

#383,920 listings for 2024 year
len(list2024)

383920

In [4]:
list1x = pd.read_csv("CRMLSListing202501.csv")
list2x = pd.read_csv("CRMLSListing202502.csv")
list3x = pd.read_csv("CRMLSListing202503.csv")
list4x = pd.read_csv("CRMLSListing202504.csv")
list5x = pd.read_csv("CRMLSListing202505.csv")
list6x = pd.read_csv("CRMLSListing202506.csv")
list7x = pd.read_csv("CRMLSListing202507.csv")
list8x = pd.read_csv("CRMLSListing202508.csv")
list9x = pd.read_csv("CRMLSListing202509.csv")
list10x = pd.read_csv("CRMLSListing202510.csv")
list11x = pd.read_csv("CRMLSListing202511.csv")
list12x = pd.read_csv("CRMLSListing202512.csv")

list2025 = pd.concat([list1x,list2x,list3x,list4x,list5x,list6x,list7x,list8x,list9x,list10x,list11x,list12x])

#363,315 listings for 2025 year
len(list2025)

363315

In [5]:
list1y = pd.read_csv("CRMLSListing202601.csv")
list2y = pd.read_csv("CRMLSListing202602.csv")
list3y = pd.read_csv("CRMLSListing202603.csv")
list4y = pd.read_csv("CRMLSListing202604.csv")
list5y = pd.read_csv("CRMLSListing202605.csv")

list2026 = pd.concat([list1y,list2y,list3y,list4y,list5y])

#182,333 listings for 2026 year
len(list2026)

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_34445/1760625872.py:2: DtypeWarning: Columns (32,58,63,66) have mixed types. Specify dtype option on import or set low_memory=False.
  list2y = pd.read_csv("CRMLSListing202602.csv")

182333

In [6]:
list = pd.concat([list2024,list2025,list2026])
print(list)

#total of 929,568 listings for years 2024, 2025, and 2026
len(list)

       OriginalListPrice  ListingKey                        ListAgentEmail  \
0                90000.0  1075010398                miriamlara03@gmail.com
1              1500000.0  1074974457                  janelle@judsonre.com
2              1340000.0  1074973329                    haleh360@Gmail.com
3              2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4              3150000.0  1074936537                      anader@dppre.com
...                  ...         ...                                   ...
35969          1500000.0  1153629738                                   NaN
35970         13999999.0  1153102507                                   NaN
35971           637000.0  1151741919                                   NaN
35972           499999.0  1146590110                                   NaN
35973           345000.0  1136798684                                   NaN

        CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0             NaN         NaN             Miriam              Lara  34.097939
1             NaN         NaN            Janelle            Judson  33.121241
2             NaN         NaN              Haleh       Dowlatshahi  34.052207
3             NaN         NaN              Renee              Chen  33.496363
4             NaN         NaN           Margaret             Nader  34.119345
...           ...         ...                ...               ...        ...
35969         NaN         NaN             Thomas             Levin  32.954514
35970  2026-06-15  14500000.0            Heather             Rocha        NaN
35971         NaN         NaN           Griselda          Espinoza  33.944936
35972         NaN         NaN              Kerry       Christenson  33.262347
35973         NaN         NaN               Leah              Cole  33.236378

        Longitude                UnparsedAddress  ... MainLevelBedrooms  \
0     -117.909653                1045 N Azusa 61  ...               NaN
1     -117.081614                            NaN  ...               NaN
2     -118.408445  2220 Avenue Of The Stars 2704  ...               NaN
3     -117.691677                   16 Palisades  ...               0.0
4     -118.111254              1615 Waverly Road  ...               NaN
...           ...                            ...  ...               ...
35969 -117.113154               12970 La Tortola  ...               NaN
35970         NaN              5516 LA CRESCENTA  ...               NaN
35971 -118.268552             327 E 101st Street  ...               NaN
35972 -116.386675            437 Ocotillo Circle  ...               NaN
35973 -117.315097               176 Flicker Lane  ...               2.0

       NewConstructionYN  GarageSpaces       HighSchoolDistrict PostalCode  \
0                    NaN           2.0    Covina Valley Unified      91722
1                    NaN           NaN                      NaN      92025
2                  False           NaN                      NaN      90067
3                  False           3.0       Capistrano Unified      92677
4                    NaN           2.0                      NaN      91108
...                  ...           ...                      ...        ...
35969              False           2.0                      NaN      92129
35970              False           4.0                      NaN      92067
35971              False           NaN                      NaN      90003
35972                NaN           2.0  Borrego Springs Unified      92004
35973              False           0.0        Oceanside Unified      92057

                    BuyerOfficeName.1 AssociationFee LotSizeSquareFeet  \
0                                 NaN            0.0               NaN
1                                 NaN            0.0               NaN
2                                 NaN         2105.0          177861.0
3                                 NaN          254.0            5300.0
4                                 NaN            NaN            9404.0
...                               ...            ...               ...
35969                             NaN            NaN            7534.0
35970  Pacific Sotheby's Int'l Realty            NaN          168577.0
35971                             NaN            NaN            5176.0
35972                             NaN            0.0           60984.0
35973                             NaN          175.0            1900.0

      MiddleOrJuniorSchoolDistrict              UnparsedAddress.1
0                              NaN                1045 N Azusa 61
1                              NaN                            NaN
2                              NaN  2220 Avenue Of The Stars 2704
3                              NaN                   16 Palisades
4                              NaN              1615 Waverly Road
...                            ...                            ...
35969                          NaN               12970 La Tortola
35970                          NaN              5516 LA CRESCENTA
35971                          NaN             327 E 101st Street
35972                          NaN            437 Ocotillo Circle
35973                          NaN               176 Flicker Lane

[929568 rows x 84 columns]

929568

In [7]:
list_residentials = list[list["PropertyType"] == "Residential"]
list_residentials

#total of 591,465 listings that were residential for years 2024, 2025, and 2026

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaN,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,1.0,False,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaN,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,3.0,False,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35969,1500000.0,1153629738,NaN,NaN,NaN,Thomas,Levin,32.954514,-117.113154,12970 La Tortola,...,NaN,False,2.0,NaN,92129,NaN,NaN,7534.0,NaN,12970 La Tortola
35970,13999999.0,1153102507,NaN,2026-06-15,14500000.0,Heather,Rocha,NaN,NaN,5516 LA CRESCENTA,...,NaN,False,4.0,NaN,92067,Pacific Sotheby's Int'l Realty,NaN,168577.0,NaN,5516 LA CRESCENTA
35971,637000.0,1151741919,NaN,NaN,NaN,Griselda,Espinoza,33.944936,-118.268552,327 E 101st Street,...,NaN,False,NaN,NaN,90003,NaN,NaN,5176.0,NaN,327 E 101st Street
35972,499999.0,1146590110,NaN,NaN,NaN,Kerry,Christenson,33.262347,-116.386675,437 Ocotillo Circle,...,NaN,NaN,2.0,Borrego Springs Unified,92004,NaN,0.00,60984.0,NaN,437 Ocotillo Circle
35973,345000.0,1136798684,NaN,NaN,NaN,Leah,Cole,33.236378,-117.315097,176 Flicker Lane,...,2.0,False,0.0,Oceanside Unified,92057,NaN,175.00,1900.0,NaN,176 Flicker Lane

##### Read all of the Sold files from 2024, 2025, and 2026. Removed the last two columns in the files named "filled." After cleaning this part of the data, performed the same code as the Listing data to combine all the datasets into one large csv file for Sold data.

In [8]:
sold1 = pd.read_csv("CRMLSSold202401.csv")
sold2 = pd.read_csv("CRMLSSold202402.csv")
sold3 = pd.read_csv("CRMLSSold202403.csv")
sold4 = pd.read_csv("CRMLSSold202404.csv")

sold5 = pd.read_csv("CRMLSSold202405_filled.csv")
sold5_new = sold5.drop(columns=sold5.columns[-2:])

sold6 = pd.read_csv("CRMLSSold202406_filled.csv")
sold6_new = sold6.drop(columns=sold6.columns[-2:])

sold7 = pd.read_csv("CRMLSSold202407_filled.csv")
sold7_new = sold1.drop(columns=sold1.columns[-2:])

sold8 = pd.read_csv("CRMLSSold202408.csv")
sold9 = pd.read_csv("CRMLSSold202409.csv")
sold10 = pd.read_csv("CRMLSSold202410.csv")
sold11 = pd.read_csv("CRMLSSold202411.csv")
sold12 = pd.read_csv("CRMLSSold202412.csv")

sold2024 = pd.concat([sold1,sold2,sold3,sold4,sold5_new,sold6_new,sold7_new,sold8,sold9,sold10,sold11,sold12])

#264,227 sold in 2024 year
len(sold2024)

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_34445/2463208298.py:4: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold4 = pd.read_csv("CRMLSSold202404.csv")

264227

In [9]:
sold1x = pd.read_csv("CRMLSSold202501_filled.csv")
sold1_newx = sold1x.drop(columns=sold1x.columns[-2:])

sold2x = pd.read_csv("CRMLSSold202502.csv")
sold3x = pd.read_csv("CRMLSSold202503.csv")
sold4x = pd.read_csv("CRMLSSold202504.csv")
sold5x = pd.read_csv("CRMLSSold202505.csv")
sold6x = pd.read_csv("CRMLSSold202506.csv")
sold7x = pd.read_csv("CRMLSSold202507.csv")
sold8x = pd.read_csv("CRMLSSold202508.csv")
sold9x = pd.read_csv("CRMLSSold202509.csv")
sold10x = pd.read_csv("CRMLSSold202510.csv")
sold11x = pd.read_csv("CRMLSSold202511.csv")
sold12x = pd.read_csv("CRMLSSold202512.csv")

sold2025 = pd.concat([sold1_newx,sold2x,sold3x,sold4x,sold5x,sold6x,sold7x,sold8x,sold9x,sold10x,sold11x,sold12x])

#260,104 sold in 2025 year
len(sold2025)

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_34445/942408989.py:8: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  sold6x = pd.read_csv("CRMLSSold202506.csv")

260104

In [10]:
sold1y = pd.read_csv("CRMLSSold202601.csv")
sold2y = pd.read_csv("CRMLSSold202602.csv")
sold3y = pd.read_csv("CRMLSSold202603.csv")
sold4y = pd.read_csv("CRMLSSold202604.csv")
sold5y = pd.read_csv("CRMLSSold202605.csv")

sold2026 = pd.concat([sold1y,sold2y,sold3y,sold4y,sold5y])

#107,344 sold in 2026 year
len(sold2026)

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_34445/2460209356.py:1: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold1y = pd.read_csv("CRMLSSold202601.csv")

107344

In [11]:
sold = pd.concat([sold2024,sold2025,sold2026])
print(sold)

#total 631,675 sold in the years 2024, 2025, and 2026
len(sold)

                  BuyerAgentAOR              ListAgentAOR          Flooring  \
0                   Mlslistings               Mlslistings  Carpet,Tile,Wood
1                    HighDesert                HighDesert               NaN
2                  OrangeCounty              OrangeCounty               NaN
3                 InlandValleys             InlandValleys               NaN
4      SouthwestRiversideCounty  SouthwestRiversideCounty               NaN
...                         ...                       ...               ...
24209                     Mrmls              OrangeCounty             Vinyl
24210           RanchoSoutheast           RanchoSoutheast               NaN
24211                  Oroville                  Oroville               NaN
24212                  Oroville                  Oroville               NaN
24213                     Mrmls        NorthSanLuisObispo               NaN

      ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  \
0       True          NaN        NaN         False           499000.0
1        NaN          NaN        NaN           NaN                0.0
2       True          NaN        NaN           NaN            75000.0
3       True          NaN        NaN           NaN           199000.0
4       True          NaN        NaN           NaN            19500.0
...      ...          ...        ...           ...                ...
24209   True          NaN        NaN         False             9000.0
24210  False          NaN        NaN         False           369000.0
24211   True          NaN        NaN           NaN          2650000.0
24212    NaN          NaN        NaN           NaN          2650000.0
24213  False          NaN        NaN           NaN          5000000.0

       ListingKey              ListAgentEmail  ... GarageSpaces  \
0       551985747       jwachter@cbnorcal.com  ...          1.0
1       535486633  eabrown@lee-associates.com  ...          NaN
2       529986282             Joe@9WINWIN.com  ...          NaN
3       529618166    carolthefinder@yahoo.com  ...          NaN
4       522614340      jtavisola@tavisola.com  ...          NaN
...           ...                         ...  ...          ...
24209   526381818                         NaN  ...          2.0
24210   497817474                         NaN  ...          0.0
24211   447028987                         NaN  ...          NaN
24212   447028983                         NaN  ...          NaN
24213   425781836                         NaN  ...          NaN

        HighSchoolDistrict PostalCode AssociationFee  LotSizeSquareFeet  \
0                    Other      94401         6472.0                NaN
1                      NaN      92394            NaN            52320.0
2                      NaN      93240            NaN           217364.0
3                      NaN      92308            NaN           217800.0
4                      NaN      93544            0.0           108883.0
...                    ...        ...            ...                ...
24209   Capistrano Unified      92677            NaN             5760.0
24210  Los Angeles Unified      90003            0.0             5202.0
24211                  NaN      95968            0.0         31798800.0
24212                  NaN      95965            NaN         31798800.0
24213                  NaN      93422            0.0           689554.8

       MiddleOrJuniorSchoolDistrict OriginatingSystemName  \
0                               NaN                 CRMLS
1                               NaN                 CRMLS
2                               NaN                 CRMLS
3                               NaN                 CRMLS
4                               NaN                 CRMLS
...                             ...                   ...
24209                           NaN                 CRMLS
24210                           NaN                 CRMLS
24211                           NaN                 CRMLS
24212                           NaN                 CRMLS
24213                           NaN                 CRMLS

      OriginatingSystemSubName  BuyerAgencyCompensationType  \
0                   CRMLS_MLSL                          NaN
1                    CRMLS_CRM                          NaN
2                    CRMLS_CRM                          NaN
3                    CRMLS_CRM                          NaN
4                    CRMLS_CRM                          NaN
...                        ...                          ...
24209                CRMLS_CRM                          NaN
24210                CRMLS_CRM                          NaN
24211                CRMLS_CRM                          NaN
24212                CRMLS_CRM                          NaN
24213                CRMLS_CRM                          NaN

       BuyerAgencyCompensation
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
...                        ...
24209                      NaN
24210                      NaN
24211                      NaN
24212                      NaN
24213                      NaN

[631675 rows x 82 columns]

631675

In [12]:
sold_residentials = sold[sold["PropertyType"] == "Residential"]
sold_residentials

#total of 591,465 sold that were residential for years 2024, 2025, and 2026

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,1.0,Other,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,2.0,NaN,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,2.0,NaN,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN
28,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,2.0,Palm Springs Unified,92262,NaN,13504.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN
29,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,2.0,Los Angeles Unified,91356,0.0,17873.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24182,NaN,VenturaCoastal,Wood,True,NaN,NaN,False,3500000.0,1063517703,NaN,...,2.0,NaN,93060,NaN,3117589.2,NaN,CRMLS,CRMLS_CRF,NaN,NaN
24190,Southland,Southland,Wood,True,NaN,NaN,False,675000.0,1052367803,NaN,...,2.0,Los Angeles Unified,91345,0.0,7039.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN
24192,ContraCosta,ContraCosta,"Carpet,SeeRemarks,Stone,Wood",NaN,NaN,True,False,35000000.0,1048618285,NaN,...,24.0,NaN,94507,3039.0,935669.0,NaN,CRMLS,CRMLS_CCBE,NaN,NaN
24206,BeverlyHillsGreaterLa,SouthBay,NaN,False,NaN,NaN,True,499000.0,1020935560,NaN,...,3.0,Los Angeles Unified,91316,504.0,30457.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN
24210,RanchoSoutheast,RanchoSoutheast,NaN,False,NaN,NaN,False,369000.0,497817474,NaN,...,0.0,Los Angeles Unified,90003,0.0,5202.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN

### Saving combined listings and sold residential properties as CSV files

In [13]:
list_residentials.to_csv("list_residentials.csv", index=False)
sold_residentials.to_csv("sold_residentials.csv", index=False)