# Week 6 Deliverable

In [1]:
import pandas as pd

In [2]:
sold = pd.read_csv("sold_clean_week45.csv")
list = pd.read_csv("list_clean_week45.csv")

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_21271/1084228439.py:1: DtypeWarning: Columns (0,1,7,51,63,64,65) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("sold_clean_week45.csv")
/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_21271/1084228439.py:2: DtypeWarning: Columns (2,39) have mixed types. Specify dtype option on import or set low_memory=False.
  list = pd.read_csv("list_clean_week45.csv")

### Creating Key Metrics

In [3]:
#Price Ratio metric for sold and list
sold["PriceRatio"] = sold["ClosePrice"]/sold["OriginalListPrice"]
list["PriceRatio"] = list["ClosePrice"]/list["OriginalListPrice"]

In [4]:
#Price per square foot metric for sold and list
sold["PricePerSqFt"] = sold["ClosePrice"]/sold["LivingArea"]
list["PricePerSqFt"] = list["ClosePrice"]/list["LivingArea"]

In [ ]:
#DaysOnMarket already exists in both datasets, so will use the original one and not make a new engineered metric

In [5]:
#Year, Month, YrMo metrics for sold and list
sold["CloseDate"] = pd.to_datetime(sold["CloseDate"], errors="coerce")
sold["Year"] = sold["CloseDate"].dt.year
sold["Month"] = sold["CloseDate"].dt.month
sold["YrMo"] = sold["CloseDate"].dt.to_period("M").astype(str)


list["CloseDate"] = pd.to_datetime(list["CloseDate"], errors="coerce")
list["Year"] = list["CloseDate"].dt.year
list["Month"] = list["CloseDate"].dt.month
list["YrMo"] = list["CloseDate"].dt.to_period("M").astype(str)

In [6]:
#Close to Original list ratio metric for sold and list
sold["ClosetoOGList"] = sold["ClosePrice"]/sold["OriginalListPrice"]
list["ClosetoOGList"] = list["ClosePrice"]/list["OriginalListPrice"]

In [7]:
#Listing to Contract Days metric for sold and list
sold["PurchaseContractDate"] = pd.to_datetime(sold["PurchaseContractDate"], errors="coerce")
sold["ListingContractDate"] = pd.to_datetime(sold["ListingContractDate"], errors="coerce")

sold["ListingtoContract"] = (sold["PurchaseContractDate"] - sold["ListingContractDate"]).dt.days


list["PurchaseContractDate"] = pd.to_datetime(list["PurchaseContractDate"], errors="coerce")
list["ListingContractDate"] = pd.to_datetime(list["ListingContractDate"], errors="coerce")

list["ListingtoContract"] = (list["PurchaseContractDate"] - list["ListingContractDate"]).dt.days

In [8]:
#Contract to Close Days metric for sold and list
sold["ContractCloseDays"] = (sold["CloseDate"]-sold["PurchaseContractDate"]).dt.days
list["ContractCloseDays"] = (list["CloseDate"]-list["PurchaseContractDate"]).dt.days

In [9]:
#Sample Output Table with the New Columns in sold
sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,positive_long_flag,implausible_coord_flag,PriceRatio,PricePerSqFt,Year,Month,YrMo,ClosetoOGList,ListingtoContract,ContractCloseDays
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,False,False,0.480962,210.526316,2024,1,2024-01,0.480962,777.0,65.0
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,False,False,1.072510,412.867275,2024,1,2024-01,1.072510,114.0,919.0
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,False,False,1.094743,410.334347,2024,1,2024-01,1.094743,255.0,778.0
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,False,False,NaN,430.075188,2024,1,2024-01,NaN,188.0,-188.0
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,False,False,1.000000,591.891046,2024,1,2024-01,1.000000,0.0,0.0

In [10]:
#Sample Output Table with the New Columns in list
list.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,positive_long_flag,implausible_coord_flag,PriceRatio,PricePerSqFt,Year,Month,YrMo,ClosetoOGList,ListingtoContract,ContractCloseDays
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,False,False,NaN,NaN,NaN,NaN,NaT,NaN,127.0,NaN
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,False,False,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,False,False,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,False,False,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,False,False,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

### Segmented Analysis

In [11]:
#Property types segment analysis
property = sold.groupby(["PropertyType","PropertySubType"])[[
    "PriceRatio","PricePerSqFt","DaysOnMarket","Year","Month",
    "YrMo","ClosetoOGList","ListingtoContract","ContractCloseDays"
]].describe()

property

/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

                                   PriceRatio                            \
                                        count        mean           std
PropertyType PropertySubType
Residential  BoatSlip                    88.0    0.915778      0.121723
             Cabin                      475.0    0.896439      0.296837
             CoOwnership                 17.0   59.803240    242.341902
             Condominium              69897.0   25.213352   4251.851849
             DeededParking                5.0    0.788298      0.444343
             Duplex                    2349.0  415.306802  20059.663735
             Farm                        17.0    0.945288      0.093478
             Loft                        30.0    0.983113      0.054194
             ManufacturedHome            40.0    0.956279      0.059150
             ManufacturedOnLand        5469.0    1.280874     17.367407
             MixedUse                   213.0    0.891491      0.158717
             MobileHome                  55.0    0.884347      0.095160
             OwnYourOwn                  63.0    1.075057      1.152741
             Quadruplex                 153.0    0.986454      0.714870
             SingleFamilyResidence   316504.0         inf           NaN
             StockCooperative          1686.0    1.538891     23.286726
             Studio                      11.0    0.957300      0.045511
             Timeshare                   19.0    0.914272      0.167824
             Townhouse                24797.0   40.613434   6130.906069
             Triplex                    356.0    1.026570      0.843094

                                                                            \
                                         min       25%       50%       75%
PropertyType PropertySubType
Residential  BoatSlip               0.086486  0.880411  0.939697  1.000000
             Cabin                  0.090909  0.813334  0.912390  0.993097
             CoOwnership            0.880000  0.938824  0.974290  1.000000
             Condominium            0.000536  0.950549  0.985612  1.002004
             DeededParking          0.001000  0.900000  0.960000  1.017771
             Duplex                 0.096000  0.930723  0.983051  1.010909
             Farm                   0.791667  0.890911  0.925000  1.007474
             Loft                   0.874074  0.960621  0.982307  1.001058
             ManufacturedHome       0.777551  0.922748  0.949359  1.000000
             ManufacturedOnLand     0.000980  0.905109  0.969697  1.000000
             MixedUse               0.008891  0.825799  0.933458  1.000000
             MobileHome             0.563158  0.857487  0.910747  0.957342
             OwnYourOwn             0.606061  0.885250  0.948276  1.000000
             Quadruplex             0.586552  0.872727  0.946667  1.000000
             SingleFamilyResidence  0.000000  0.953846  1.000000  1.023294
             StockCooperative       0.451111  0.947368  0.984604  1.000000
             Studio                 0.909091  0.921088  0.940476  1.000000
             Timeshare              0.454545  0.959557  0.988736  1.000000
             Townhouse              0.000932  0.965914  1.000000  1.019052
             Triplex                0.497143  0.897551  0.973442  1.002937

                                                 PricePerSqFt               \
                                             max        count         mean
PropertyType PropertySubType
Residential  BoatSlip               1.045151e+00         47.0  1903.183084
             Cabin                  6.589147e+00        475.0   612.077746
             CoOwnership            1.000227e+03         17.0   490.750455
             Condominium            9.457364e+05      69977.0          inf
             DeededParking          1.062721e+00          4.0   410.512905
             Duplex                 9.722222e+05       2349.0   639.505477
             Farm                   1.138952e+00         18.0   850.627127
             Loft                   1.132265e+00         30.0   551.037557
             ManufacturedHome       1.116883e+00         40.0   199.122470
             ManufacturedOnLand     1.000000e+03       5469.0          inf
             MixedUse               1.500000e+00        212.0   504.034269
             MobileHome             9.826087e-01         55.0          inf
             OwnYourOwn             1.004444e+01         63.0          inf
             Quadruplex             9.652510e+00        153.0   445.797346
             SingleFamilyResidence           inf     316978.0          inf
             StockCooperative       9.571429e+02       1686.0   406.967357
             Studio                 1.030303e+00         11.0   692.592624
             Timeshare              1.000000e+00         19.0   289.634640
             Townhouse              9.653846e+05      24838.0   659.331806
             Triplex                1.090000e+01        356.0   583.210916

                                    ... ListingtoContract           \
                                    ...               75%      max
PropertyType PropertySubType        ...
Residential  BoatSlip               ...            102.50    322.0
             Cabin                  ...            127.50    886.0
             CoOwnership            ...             68.00    168.0
             Condominium            ...             66.00   7325.0
             DeededParking          ...             31.00     68.0
             Duplex                 ...             73.00   1229.0
             Farm                   ...             55.00    394.0
             Loft                   ...             93.25    283.0
             ManufacturedHome       ...             85.00    174.0
             ManufacturedOnLand     ...             94.00   1099.0
             MixedUse               ...            122.00    833.0
             MobileHome             ...            125.50    350.0
             OwnYourOwn             ...            110.50    337.0
             Quadruplex             ...            106.00    469.0
             SingleFamilyResidence  ...             57.00  14657.0
             StockCooperative       ...             69.00    674.0
             Studio                 ...            103.00    157.0
             Timeshare              ...            127.50    206.0
             Townhouse              ...             50.00   1374.0
             Triplex                ...             89.25    611.0

                                   ContractCloseDays                         \
                                               count       mean         std
PropertyType PropertySubType
Residential  BoatSlip                           88.0  18.931818   13.588193
             Cabin                             475.0  35.261053   27.545575
             CoOwnership                        17.0  55.117647   42.482176
             Condominium                     69949.0  30.936096  140.407643
             DeededParking                       5.0  29.000000   17.306068
             Duplex                           2349.0  38.420605   28.841800
             Farm                               18.0  73.222222  104.948478
             Loft                               30.0  38.766667   23.411879
             ManufacturedHome                   40.0  40.450000   25.208820
             ManufacturedOnLand               5469.0  40.469007   38.330394
             MixedUse                          213.0  47.680751   51.959813
             MobileHome                         55.0  14.709091   14.083971
             OwnYourOwn                         63.0  35.253968   37.033537
             Quadruplex                        153.0  41.771242   27.131380
             SingleFamilyResidence          317006.0  31.622808   26.077687
             StockCooperative                 1686.0  47.283511   17.141348
             Studio                             11.0  38.272727   17.263203
             Timeshare                          19.0  26.894737   28.163993
             Townhouse                       24834.0  31.040147   24.619383
             Triplex                           356.0  44.710674   46.136515


                                      min    25%   50%    75%      max
PropertyType PropertySubType
Residential  BoatSlip                 0.0  11.75  16.0  23.25    101.0
             Cabin                    0.0  21.00  30.0  41.00    296.0
             CoOwnership             11.0  31.00  40.0  59.00    150.0
             Condominium            -19.0  20.00  28.0  35.00  36629.0
             DeededParking            3.0  23.00  31.0  40.00     48.0
             Duplex                   0.0  23.00  32.0  45.00    352.0
             Farm                     0.0  22.00  31.0  85.00    461.0
             Loft                    13.0  22.25  34.5  43.75    110.0
             ManufacturedHome        13.0  23.75  30.5  48.25    118.0
             ManufacturedOnLand       0.0  24.00  34.0  48.00   1281.0
             MixedUse                 0.0  21.00  32.0  62.00    557.0
             MobileHome               1.0   2.00  12.0  21.00     62.0
             OwnYourOwn             -61.0  18.00  29.0  36.50    181.0
             Quadruplex               0.0  25.00  36.0  53.00    227.0
             SingleFamilyResidence -331.0  21.00  29.0  36.00   1970.0
             StockCooperative         0.0  39.00  45.0  53.00    293.0
             Studio                  10.0  31.50  33.0  44.00     77.0
             Timeshare                0.0  10.00  15.0  36.50    112.0
             Townhouse              -61.0  21.00  28.0  34.00    535.0
             Triplex                  0.0  26.00  35.0  50.00    605.0

[20 rows x 64 columns]

In [12]:
#Area types segment analysis
area = sold.groupby(["CountyOrParish","MLSAreaMajor"])[[
    "PriceRatio","PricePerSqFt","DaysOnMarket","Year","Month",
    "YrMo","ClosetoOGList","ListingtoContract","ContractCloseDays"
]].describe()

area

                                     PriceRatio                         \
                                          count       mean         std
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined         1793.0   1.029925    0.101063
               BERK - Berkeley              3.0   1.090453    0.186561
Amador         699 - Not Defined            5.0   0.890853    0.052264
Butte          699 - Not Defined           55.0  19.822386  139.965470
               PARA - Paradise             62.0   0.958491    0.096118
...                                         ...        ...         ...
Ventura        WEH - West Hills             1.0   1.075001         NaN
               WV - Westlake Village      730.0   0.973688    0.346046
               WW - Wagon Wheel             2.0   0.966142    0.038391
Yolo           699 - Not Defined           18.0   1.006178    0.132277
Yuba           699 - Not Defined           10.0   0.921573    0.061204

                                                                              \
                                           min       25%       50%       75%
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined      0.674710  0.971154  1.013409  1.076471
               BERK - Berkeley        0.966361  0.983180  1.000000  1.152499
Amador         699 - Not Defined      0.833333  0.867826  0.889054  0.889054
Butte          699 - Not Defined      0.666667  0.926115  0.965161  1.000000
               PARA - Paradise        0.581818  0.941613  0.973165  1.000000
...                                        ...       ...       ...       ...
Ventura        WEH - West Hills       1.075001  1.075001  1.075001  1.075001
               WV - Westlake Village  0.481207  0.933333  0.973029  1.000000
               WW - Wagon Wheel       0.938996  0.952569  0.966142  0.979715
Yolo           699 - Not Defined      0.906736  0.941925  0.971569  1.010788
Yuba           699 - Not Defined      0.848000  0.870041  0.923704  0.975271

                                                  PricePerSqFt              \
                                              max        count        mean
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined         1.954355       1813.0  772.218892
               BERK - Berkeley           1.304998          3.0  576.712240
Amador         699 - Not Defined         0.975000          6.0  207.368222
Butte          699 - Not Defined      1038.961039         55.0  251.778670
               PARA - Paradise           1.182007         62.0  261.152370
...                                           ...          ...         ...
Ventura        WEH - West Hills          1.075001          1.0  379.858657
               WV - Westlake Village    10.121245        730.0  694.490661
               WW - Wagon Wheel          0.993289          2.0  349.157414
Yolo           699 - Not Defined         1.500000         18.0  334.769823
Yuba           699 - Not Defined         1.000000         10.0  288.025752

                                      ... ListingtoContract         \
                                      ...               75%    max
CountyOrParish MLSAreaMajor           ...
Alameda        699 - Not Defined      ...             31.00  585.0
               BERK - Berkeley        ...             67.50  123.0
Amador         699 - Not Defined      ...             99.00  162.0
Butte          699 - Not Defined      ...             97.50  346.0
               PARA - Paradise        ...            125.50  361.0
...                                   ...               ...    ...
Ventura        WEH - West Hills       ...             16.00   16.0
               WV - Westlake Village  ...             77.00  567.0
               WW - Wagon Wheel       ...             56.75   69.0
Yolo           699 - Not Defined      ...             65.50  140.0
Yuba           699 - Not Defined      ...            217.50  305.0

                                     ContractCloseDays                        \
                                                 count       mean        std
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined                1813.0  28.265306  30.070460
               BERK - Berkeley                     3.0  28.333333  11.239810
Amador         699 - Not Defined                   6.0  14.833333  28.230598
Butte          699 - Not Defined                  55.0  37.527273  28.523450
               PARA - Paradise                    62.0  37.032258  22.503164
...                                                ...        ...        ...
Ventura        WEH - West Hills                    1.0  68.000000        NaN
               WV - Westlake Village             729.0  22.436214  24.602926
               WW - Wagon Wheel                    2.0  21.500000  10.606602
Yolo           699 - Not Defined                  18.0  35.388889  26.520001
Yuba           699 - Not Defined                  10.0  35.600000  10.330107


                                       min    25%   50%    75%    max
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined      -9.0  21.00  26.0  30.00  543.0
               BERK - Berkeley        16.0  23.50  31.0  34.50   38.0
Amador         699 - Not Defined     -25.0   3.00  10.5  29.25   57.0
Butte          699 - Not Defined      10.0  24.00  31.0  40.50  210.0
               PARA - Paradise         0.0  26.25  30.0  45.75  151.0
...                                    ...    ...   ...    ...    ...
Ventura        WEH - West Hills       68.0  68.00  68.0  68.00   68.0
               WV - Westlake Village   0.0   7.00  18.0  31.00  316.0
               WW - Wagon Wheel       14.0  17.75  21.5  25.25   29.0
Yolo           699 - Not Defined       7.0  21.25  27.0  40.50  103.0
Yuba           699 - Not Defined      27.0  29.25  33.0  35.00   62.0

[1236 rows x 64 columns]

In [13]:
#office types segment analysis
office = sold.groupby(["ListOfficeName","BuyerOfficeName"])[[
    "PriceRatio","PricePerSqFt","DaysOnMarket","Year","Month",
    "ClosetoOGList","ListingtoContract","ContractCloseDays"
]].mean()

office

                                                           PriceRatio  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                   0.947368
                           REALTYX                           1.022388
                           Ricky&Jessie Realty               0.979275
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT    1.078582
                           ROA California Inc                0.835836
...                                                               ...
uDream Real Estate         NONMEMBER MRML                    1.017056
                           REALTY MASTERS & ASSOCIATES       1.001757
zRE Group                  Pacific Sotheby's Int'l Realty    1.000000
                           Team Laguna Inc                   0.945312
                           zRE Group                         1.020408

                                                           PricePerSqFt  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                   483.610962
                           REALTYX                           685.000000
                           Ricky&Jessie Realty               507.791510
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT    280.000000
                           ROA California Inc                347.916667
...                                                                 ...
uDream Real Estate         NONMEMBER MRML                    248.201439
                           REALTY MASTERS & ASSOCIATES       292.908530
zRE Group                  Pacific Sotheby's Int'l Realty   1787.463271
                           Team Laguna Inc                  1996.699670
                           zRE Group                         556.792873

                                                           DaysOnMarket  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                         14.0
                           REALTYX                                 24.0
                           Ricky&Jessie Realty                     24.0
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT          18.0
                           ROA California Inc                      95.0
...                                                                 ...
uDream Real Estate         NONMEMBER MRML                           9.0
                           REALTY MASTERS & ASSOCIATES             73.0
zRE Group                  Pacific Sotheby's Int'l Realty          13.0
                           Team Laguna Inc                        130.0
                           zRE Group                               21.0

                                                             Year  Month  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                 2025.0    7.0
                           REALTYX                         2026.0    4.0
                           Ricky&Jessie Realty             2025.0   12.0
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT  2026.0    4.0
                           ROA California Inc              2025.0    3.0
...                                                           ...    ...
uDream Real Estate         NONMEMBER MRML                  2024.0   11.0
                           REALTY MASTERS & ASSOCIATES     2024.0    6.0
zRE Group                  Pacific Sotheby's Int'l Realty  2026.0    1.0
                           Team Laguna Inc                 2026.0    1.0
                           zRE Group                       2026.0    5.0

                                                           ClosetoOGList  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                      0.947368
                           REALTYX                              1.022388
                           Ricky&Jessie Realty                  0.979275
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT       1.078582
                           ROA California Inc                   0.835836
...                                                                  ...
uDream Real Estate         NONMEMBER MRML                       1.017056
                           REALTY MASTERS & ASSOCIATES          1.001757
zRE Group                  Pacific Sotheby's Int'l Realty       1.000000
                           Team Laguna Inc                      0.945312
                           zRE Group                            1.020408

                                                           ListingtoContract  \
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                              17.0
                           REALTYX                                      27.0
                           Ricky&Jessie Realty                          24.0
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT               39.0
                           ROA California Inc                           96.0
...                                                                      ...
uDream Real Estate         NONMEMBER MRML                               14.0
                           REALTY MASTERS & ASSOCIATES                  78.0
zRE Group                  Pacific Sotheby's Int'l Realty               13.0
                           Team Laguna Inc                             134.0
                           zRE Group                                    21.0

                                                           ContractCloseDays
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                              28.0
                           REALTYX                                      25.0
                           Ricky&Jessie Realty                          36.0
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT               34.0
                           ROA California Inc                           21.0
...                                                                      ...
uDream Real Estate         NONMEMBER MRML                               28.0
                           REALTY MASTERS & ASSOCIATES                  22.0
zRE Group                  Pacific Sotheby's Int'l Realty               53.0
                           Team Laguna Inc                              23.0
                           zRE Group                                    15.0

[210216 rows x 8 columns]

### Adding School Districts

In [ ]:
import geopandas as gpd
from shapely.geometry import Point

school_dists = gpd.read_file("DistrictAreas2425.zip")
print(school_dists.columns)

Index(['OBJECTID', 'Year', 'FedID', 'CDCode', 'CDSCode', 'CountyName',
       'DistrictNa', 'DistrictTy', 'GradeLow', 'GradeHigh', 'GradeLowCe',
       'GradeHighC', 'AssistStat', 'CongressUS', 'SenateCA', 'AssemblyCA',
       'UpdateNote', 'EnrollTota', 'EnrollChar', 'EnrollNonC', 'AAcount',
       'AApct', 'AIcount', 'AIpct', 'AScount', 'ASpct', 'FIcount', 'FIpct',
       'HIcount', 'HIpct', 'PIcount', 'PIpct', 'WHcount', 'WHpct', 'MRcount',
       'MRpct', 'NRcount', 'NRpct', 'ELcount', 'ELpct', 'FOScount', 'FOSpct',
       'HOMcount', 'HOMpct', 'MIGcount', 'MIGpct', 'SWDcount', 'SWDpct',
       'SEDcount', 'SEDpct', 'DistrctAre', 'Shape__Are', 'Shape__Len',
       'geometry'],
      dtype='object')

In [34]:
sold_geographic = gpd.GeoDataFrame(sold,geometry=gpd.points_from_xy(sold.Longitude,sold.Latitude),crs="EPSG:4326")
sold_geographic = gpd.sjoin(sold_geographic,school_dists[["DistrictNa","geometry"]],how="left",predicate="within")

list_geographic = gpd.GeoDataFrame(list,geometry=gpd.points_from_xy(list.Longitude,list.Latitude),crs="EPSG:4326")
list_geographic = gpd.sjoin(list_geographic,school_dists[["DistrictNa","geometry"]],how="left",predicate="within")

/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_21271/1839920003.py:2: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:3857

  sold_geographic = gpd.sjoin(sold_geographic,school_dists[["DistrictNa","geometry"]],how="left",predicate="within")
/var/folders/y8/n1dk_n9n2fsf3cpk4z474lmc0000gn/T/ipykernel_21271/1839920003.py:5: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:3857

  list_geographic = gpd.sjoin(list_geographic,school_dists[["DistrictNa","geometry"]],how="left",predicate="within")

In [32]:
sold_geographic

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PricePerSqFt,Year,Month,YrMo,ClosetoOGList,ListingtoContract,ContractCloseDays,geometry,index_right,DistrictNa
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,210.526316,2024,1,2024-01,0.480962,777.0,65.0,POINT (NaN NaN),NaN,NaN
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,412.867275,2024,1,2024-01,1.072510,114.0,919.0,POINT (NaN NaN),NaN,NaN
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,410.334347,2024,1,2024-01,1.094743,255.0,778.0,POINT (NaN NaN),NaN,NaN
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,430.075188,2024,1,2024-01,NaN,188.0,-188.0,POINT (NaN NaN),NaN,NaN
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,591.891046,2024,1,2024-01,1.000000,0.0,0.0,POINT (-118.55875 34.16438),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423851,NaN,VenturaCoastal,Wood,True,False,3500000.0,1063517703,NaN,2026-05-08,1850000.0,...,616.666667,2026,5,2026-05,0.528571,774.0,6.0,POINT (-119.14586 34.37768),NaN,NaN
423852,Southland,Southland,Wood,True,False,675000.0,1052367803,NaN,2026-05-06,655000.0,...,649.801587,2026,5,2026-05,0.970370,581.0,296.0,POINT (-118.45237 34.27526),NaN,NaN
423853,ContraCosta,ContraCosta,"Carpet,SeeRemarks,Stone,Wood",NaN,False,35000000.0,1048618285,NaN,2026-05-15,21500000.0,...,922.192674,2026,5,2026-05,0.614286,831.0,69.0,POINT (-121.96159 37.85465),NaN,NaN
423854,BeverlyHillsGreaterLa,SouthBay,NaN,False,True,499000.0,1020935560,NaN,2026-05-22,400000.0,...,319.233839,2026,5,2026-05,0.801603,1392.0,11.0,POINT (-118.52479 34.16792),NaN,NaN
423855,RanchoSoutheast,RanchoSoutheast,NaN,False,False,369000.0,497817474,NaN,2026-05-21,410000.0,...,340.814630,2026,5,2026-05,1.111111,3.0,1956.0,POINT (-118.27128 33.96079),NaN,NaN

In [35]:
list_geographic

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,PricePerSqFt,Year,Month,YrMo,ClosetoOGList,ListingtoContract,ContractCloseDays,geometry,index_right,DistrictNa
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,NaN,NaT,NaN,127.0,NaN,POINT (-118.40844 34.05221),NaN,NaN
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-117.69168 33.49636),NaN,NaN
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-118.11125 34.11934),NaN,NaN
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-117.80282 33.98406),NaN,NaN
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-117.88774 33.60758),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591460,1500000.0,1153629738,NaN,NaT,NaN,Thomas,Levin,32.954514,-117.113154,12970 La Tortola,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-117.11315 32.95451),NaN,NaN
591461,13999999.0,1153102507,NaN,2026-06-15,14500000.0,Heather,Rocha,NaN,NaN,5516 LA CRESCENTA,...,1671.662439,2026.0,6.0,2026-06,1.035714,-1.0,32.0,POINT (NaN NaN),NaN,NaN
591462,637000.0,1151741919,NaN,NaT,NaN,Griselda,Espinoza,33.944936,-118.268552,327 E 101st Street,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-118.26855 33.94494),NaN,NaN
591463,499999.0,1146590110,NaN,NaT,NaN,Kerry,Christenson,33.262347,-116.386675,437 Ocotillo Circle,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-116.38668 33.26235),NaN,NaN
591464,345000.0,1136798684,NaN,NaT,NaN,Leah,Cole,33.236378,-117.315097,176 Flicker Lane,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,POINT (-117.3151 33.23638),NaN,NaN

### Saving Datasets as CSVs

In [36]:
sold_geographic.to_csv("soldFINALFINAL.csv", index=False)
list_geographic.to_csv("listFINALFINAL.csv", index=False)